; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\odzhan\tinycrypt\hash\crc\crc16.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_xcrc16
; Function compile flags: /Ogspy
;	COMDAT _xcrc16
_TEXT	SEGMENT
_crc$ = 8						; size = 2
_inlen$ = 12						; size = 2
_in$ = 16						; size = 4
_xcrc16	PROC						; COMDAT
; File c:\odzhan\tinycrypt\hash\crc\crc16.c
; Line 13
	push	ebp
	mov	ebp, esp
; Line 18
	cmp	WORD PTR _inlen$[ebp], 0
	mov	eax, DWORD PTR _crc$[ebp]
	not	eax
	movzx	edx, ax
	mov	DWORD PTR _crc$[ebp], edx
	je	SHORT $LN11@xcrc16
	mov	eax, DWORD PTR _in$[ebp]
	push	esi
$LL5@xcrc16:
; Line 20
	movzx	ecx, BYTE PTR [eax]
	xor	WORD PTR _crc$[ebp], cx
	add	DWORD PTR _inlen$[ebp], 65535		; 0000ffffH
	push	8
	inc	eax
	pop	ecx
$LL12@xcrc16:
; Line 23
	mov	esi, DWORD PTR _crc$[ebp]
	mov	dx, WORD PTR _crc$[ebp]
	and	esi, 1
	imul	esi, 40961				; 0000a001H
	shr	dx, 1
	xor	si, dx
	dec	ecx
	movzx	edx, si
	mov	DWORD PTR _crc$[ebp], edx
	jne	SHORT $LL12@xcrc16
; Line 18
	cmp	WORD PTR _inlen$[ebp], cx
	jne	SHORT $LL5@xcrc16
	pop	esi
$LN11@xcrc16:
; Line 26
	mov	eax, edx
	not	eax
; Line 27
	pop	ebp
	ret	0
_xcrc16	ENDP
_TEXT	ENDS
END
