; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\odzhan\tinycrypt\block\rc6\rc6.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_rc6_setkey
; Function compile flags: /Ogspy
;	COMDAT _rc6_setkey
_TEXT	SEGMENT
_L$ = -36						; size = 32
tv192 = -4						; size = 4
_key$ = 8						; size = 4
tv95 = 12						; size = 4
_K$ = 12						; size = 4
_A$ = 16						; size = 4
_keylen$ = 16						; size = 4
_rc6_setkey PROC					; COMDAT
; File c:\odzhan\tinycrypt\block\rc6\rc6.c
; Line 33
	push	ebp
	mov	ebp, esp
	sub	esp, 36					; 00000024H
; Line 37
	mov	ecx, DWORD PTR _keylen$[ebp]
	push	ebx
	shr	ecx, 2
	xor	ebx, ebx
	push	esi
	push	edi
	mov	DWORD PTR tv192[ebp], ecx
	cmp	ecx, ebx
	jbe	SHORT $LN9@rc6_setkey
	mov	esi, DWORD PTR _K$[ebp]
	lea	edi, DWORD PTR _L$[ebp]
	rep movsd
$LN9@rc6_setkey:
; Line 41
	mov	ecx, -1209970333			; b7e15163H
; Line 44
	xor	eax, eax
$LL6@rc6_setkey:
; Line 45
	mov	edx, DWORD PTR _key$[ebp]
	mov	DWORD PTR [edx+eax*4], ecx
; Line 46
	sub	ecx, 1640531527				; 61c88647H
	inc	eax
	cmp	eax, 44					; 0000002cH
	jb	SHORT $LL6@rc6_setkey
; Line 49
	xor	edi, edi
	xor	esi, esi
	mov	DWORD PTR _A$[ebp], ebx
	mov	DWORD PTR tv95[ebp], 132		; 00000084H
$LL18@rc6_setkey:
; Line 54
	mov	eax, DWORD PTR _key$[ebp]
	lea	ecx, DWORD PTR [eax+esi*4]
	mov	eax, DWORD PTR [ecx]
	add	eax, ebx
	add	eax, DWORD PTR _A$[ebp]
; Line 55
	lea	edx, DWORD PTR _L$[ebp+edi*4]
	rol	eax, 3
	mov	DWORD PTR [ecx], eax
	lea	ecx, DWORD PTR [ebx+eax]
	mov	DWORD PTR _A$[ebp], eax
	mov	eax, DWORD PTR [edx]
	add	eax, ebx
	add	eax, DWORD PTR _A$[ebp]
; Line 58
	push	44					; 0000002cH
	rol	eax, cl
	pop	ecx
	mov	DWORD PTR [edx], eax
	mov	ebx, eax
	xor	edx, edx
	lea	eax, DWORD PTR [esi+1]
	div	ecx
; Line 60
	lea	eax, DWORD PTR [edi+1]
	mov	esi, edx
; Line 61
	xor	edx, edx
	div	DWORD PTR tv192[ebp]
	dec	DWORD PTR tv95[ebp]
	mov	edi, edx
	jne	SHORT $LL18@rc6_setkey
	pop	edi
	pop	esi
	pop	ebx
; Line 63
	leave
	ret	0
_rc6_setkey ENDP
_TEXT	ENDS
PUBLIC	_rc6_crypt
; Function compile flags: /Ogspy
;	COMDAT _rc6_crypt
_TEXT	SEGMENT
tv243 = -8						; size = 4
_D$ = -4						; size = 4
tv71 = 8						; size = 4
_key$ = 8						; size = 4
_C$ = 12						; size = 4
_input$ = 12						; size = 4
_output$ = 16						; size = 4
_enc$ = 20						; size = 4
_rc6_crypt PROC						; COMDAT
; Line 66
	push	ebp
	mov	ebp, esp
	push	ecx
	push	ecx
; Line 80
	cmp	DWORD PTR _enc$[ebp], 1
	mov	eax, DWORD PTR _input$[ebp]
	mov	ecx, DWORD PTR [eax+12]
; Line 82
	mov	edx, DWORD PTR _key$[ebp]
	push	ebx
	mov	ebx, DWORD PTR [eax]
	push	esi
	mov	esi, DWORD PTR [eax+8]
	push	edi
	mov	edi, DWORD PTR [eax+4]
	mov	DWORD PTR _C$[ebp], esi
	mov	DWORD PTR _D$[ebp], ecx
	jne	SHORT $LN9@rc6_crypt
; Line 83
	add	ecx, DWORD PTR [edx+4]
	add	edi, DWORD PTR [edx]
	mov	DWORD PTR _D$[ebp], ecx
	add	edx, 8
; Line 84
	jmp	SHORT $LN8@rc6_crypt
$LN9@rc6_crypt:
; Line 86
	sub	esi, DWORD PTR [edx+172]
; Line 87
	sub	ebx, DWORD PTR [edx+168]
	mov	DWORD PTR _C$[ebp], esi
	sub	edx, -164				; ffffff5cH
$LN8@rc6_crypt:
; Line 90
	mov	DWORD PTR tv243[ebp], 20		; 00000014H
$LL7@rc6_crypt:
; Line 92
	cmp	DWORD PTR _enc$[ebp], 1
	jne	SHORT $LN4@rc6_crypt
; Line 94
	lea	esi, DWORD PTR [edi+edi+1]
	imul	esi, edi
; Line 95
	lea	eax, DWORD PTR [ecx+ecx+1]
	imul	eax, ecx
	rol	esi, 5
	rol	eax, 5
; Line 97
	mov	ecx, eax
; Line 98
	xor	eax, DWORD PTR _C$[ebp]
	mov	DWORD PTR tv71[ebp], esi
	xor	DWORD PTR tv71[ebp], ebx
	mov	ebx, DWORD PTR tv71[ebp]
	rol	ebx, cl
	mov	ecx, esi
	add	ebx, DWORD PTR [edx]
	rol	eax, cl
; Line 100
	mov	ecx, ebx
; Line 101
	mov	ebx, edi
	add	eax, DWORD PTR [edx+4]
	add	edx, 8
; Line 102
	mov	edi, eax
; Line 103
	mov	eax, DWORD PTR _D$[ebp]
	mov	DWORD PTR _C$[ebp], eax
; Line 104
	mov	DWORD PTR _D$[ebp], ecx
; Line 105
	jmp	SHORT $LN6@rc6_crypt
$LN4@rc6_crypt:
; Line 109
	sub	edi, DWORD PTR [edx]
	lea	esi, DWORD PTR [esi+esi+1]
	imul	esi, DWORD PTR _C$[ebp]
	lea	eax, DWORD PTR [ebx+ebx+1]
	imul	eax, ebx
	rol	eax, 5
	rol	esi, 5
	push	32					; 00000020H
	pop	ecx
	sub	ecx, eax
	rol	edi, cl
; Line 110
	push	32					; 00000020H
	pop	ecx
	sub	ecx, esi
	xor	edi, esi
	mov	esi, DWORD PTR _D$[ebp]
	sub	esi, DWORD PTR [edx-4]
	rol	esi, cl
	xor	esi, eax
; Line 113
	mov	eax, DWORD PTR _C$[ebp]
; Line 114
	mov	DWORD PTR _C$[ebp], edi
; Line 115
	mov	edi, ebx
	sub	edx, 8
	mov	DWORD PTR _D$[ebp], eax
; Line 116
	mov	ebx, esi
$LN6@rc6_crypt:
; Line 123
	dec	DWORD PTR tv243[ebp]
	mov	esi, DWORD PTR _C$[ebp]
; Line 124
	mov	ecx, DWORD PTR _D$[ebp]
	jne	$LL7@rc6_crypt
; Line 120
	cmp	DWORD PTR _enc$[ebp], 1
	jne	SHORT $LN2@rc6_crypt
; Line 122
	add	ebx, DWORD PTR [edx]
; Line 123
	add	esi, DWORD PTR [edx+4]
; Line 124
	jmp	SHORT $LN1@rc6_crypt
$LN2@rc6_crypt:
; Line 125
	sub	ecx, DWORD PTR [edx]
; Line 126
	sub	edi, DWORD PTR [edx-4]
$LN1@rc6_crypt:
; Line 129
	mov	eax, DWORD PTR _output$[ebp]
; Line 130
	mov	DWORD PTR [eax+4], edi
	pop	edi
; Line 131
	mov	DWORD PTR [eax+8], esi
	pop	esi
	mov	DWORD PTR [eax], ebx
; Line 132
	mov	DWORD PTR [eax+12], ecx
	pop	ebx
; Line 133
	leave
	ret	0
_rc6_crypt ENDP
_TEXT	ENDS
END
