; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\odzhan\tinycrypt\block\chaskey\chaskey.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_encrypt
; Function compile flags: /Ogspy
;	COMDAT _encrypt
_TEXT	SEGMENT
tv339 = -4						; size = 4
_v$ = 8							; size = 4
_key$ = 12						; size = 4
_encrypt PROC						; COMDAT
; File c:\odzhan\tinycrypt\block\chaskey\chaskey.c
; Line 4
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 6
	mov	eax, DWORD PTR _v$[ebp]
	mov	edx, DWORD PTR _key$[ebp]
	push	ebx
	push	esi
	push	edi
	sub	edx, eax
	push	4
	mov	ecx, eax
	mov	DWORD PTR tv339[ebp], edx
	pop	esi
$LL9@encrypt:
	mov	edi, DWORD PTR [edx+ecx]
	xor	DWORD PTR [ecx], edi
	add	ecx, 4
	dec	esi
	jne	SHORT $LL9@encrypt
; Line 7
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR [eax+4]
	mov	esi, DWORD PTR [eax+12]
	mov	edi, DWORD PTR [eax+8]
	push	8
	pop	ebx
$LL6@encrypt:
; Line 8
	add	ecx, edx
	rol	edx, 5
	xor	edx, ecx
; Line 9
	add	edi, esi
	rol	esi, 8
	xor	esi, edi
	rol	ecx, 16					; 00000010H
; Line 10
	add	ecx, esi
	rol	esi, 13					; 0000000dH
; Line 11
	add	edi, edx
	xor	esi, ecx
	rol	edx, 7
	xor	edx, edi
	rol	edi, 16					; 00000010H
	dec	ebx
	mov	DWORD PTR [eax], ecx
	jne	SHORT $LL6@encrypt
; Line 13
	push	4
	pop	ecx
	mov	DWORD PTR [eax+8], edi
	pop	edi
	mov	DWORD PTR [eax+12], esi
	pop	esi
	mov	DWORD PTR [eax+4], edx
	pop	ebx
$LL3@encrypt:
	mov	edx, DWORD PTR tv339[ebp]
	mov	edx, DWORD PTR [eax+edx]
	xor	DWORD PTR [eax], edx
	add	eax, 4
	dec	ecx
	jne	SHORT $LL3@encrypt
; Line 14
	leave
	ret	0
_encrypt ENDP
_TEXT	ENDS
END
